### ISSUE TITLE
[jest-plugin-fs] How do I unmock files which should be read?

### ISSUE THREAD

**Issue by ms88privat** [negativetwelve/jest-plugins#79]

**Comment by negativetwelve** [comment]
Hi @ms88privat, sorry for the lack of docs, I actually just added that feature. Here's an example, hope it helps:

https://github.com/negativetwelve/jest-plugins/blob/master/packages/jest-plugin-fs/src/__tests__/fs.spec.js#L80-L90

```
fs.unmock(arrayOfPathsToFilesToUnmock);
```

where `arrayOfPathsToFilesToUnmock` is an array of file paths. This reads in the actual file and inserts it into the virtual filesystem

**Comment by ms88privat** [comment]
Thank you. I got this error now: `Invalid file signature`. I'm trying to load `.png` files. Any idea?

**Comment by negativetwelve** [comment]
Ah interesting, it only works with text based files. Can you help me understand the usecase for unmocking a png file? I would love to support your use case but it'll require some changes

**Comment by ms88privat** [comment]
I'm also not so sure about my use case, I just tried to find a solution to my problem, that my jest tests are extremely slow when it comes to the file system. So I'm trying to mock it as much as possible. The real use case would be image comparison. 

This line `Jimp.read(path);` takes about 4 seconds to execute inside a jest test. If I invoke the same code via `node` it is almost instant.

**Comment by negativetwelve** [comment]
Interesting, is that line run in a `beforeEach` block? if so, it's executing once per test, not just once. To manually mock, try this (pseudo code):

```
const image = Jimp.read(path);

describe('my tests', () => {
  beforeEach(() => fs.mock({[path]: image}));

  it('should do something', () => {
    
  });
});

**Comment by negativetwelve** [comment]
basically read the image using your preferred reader outside the tests (only once), and then mocking the path with the contents of the file in the beforeEach block

**Comment by ms88privat** [comment]
I only got one test. Just reading the images takes ages. So mocking the rest afterwards will also not help. I couldn't test loading the image outside the test because I need it inside and it is also a promise.

**Comment by negativetwelve** [comment]
Going to close this issue since I think it's specific to your test. If you think otherwise, please feel free to re-open and update us on where things are at!
