### ISSUE TITLE
Remove peerDependency "jest-plugins" from jest-plugin-set

### ISSUE THREAD

**Issue by peterjuras** [negativetwelve/jest-plugins#81]
## Description

Hi! Thanks a lot for these plugins, I'm using the set plugin and it is really awesome so far!

I wanted to ask you whether you could remove the peerDependency to "jest-plugins" for the jest-plugins-set package. It appears it works without it or not? I'd like to only use that plugin for the time being.

P.S.: I created an eslint-rule which no longer marks variables declared via set as undefined:

https://github.com/peterjuras/eslint-plugin-jest-set

**Comment by negativetwelve** [comment]
Hi @peterjuras!

Thanks for the suggestion, you're absolutely right. I've submitted a PR and will deploy a new version in a few min.

Also, this eslint rule is great! I've been wanting to do that myself for a while, glad someone took the initiative and built it :)

**Comment by peterjuras** [comment]
Thank you! That was very quick =)
