### ISSUE TITLE
How to use with context plugin in TypeScript

### ISSUE THREAD

**Issue by kristianmandrup** [negativetwelve/jest-plugins#91]
I have installed the plugin and typings as dev dependencies and configured my `setupFiles` to include the context plugin. However VSC doesn't seem to recognize that `context` is available globally.
How to fix this? 

Tests pass, just VSC is not aware it is valid. Please improve the docs. 
Is this a tsconfig setting thingy? thanks.

**Comment by negativetwelve** [comment]
Hi @kristianmandrup, thanks for creating this issue.

@jonasheinrich is the contributor who created the types for the context plugin. He might be able to help figure out what the issue is. After, we can create a PR to update the docs once this is solved!

**Comment by kristianmandrup** [comment]
It worked seamlessly after a VSC restart and letting the Typescript engine take some time to figure it out. Huge project... But please update docs for Typescript in any case ;) Wasn't too clear. Thanks
